version: '3'

services:
  hello-world:
    build: .
    ports:
      - "8080:3000"

  db:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_PASSWORD: popeye
    ports:
      - "5432:5432"